apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-app
spec:
  selector:
    matchLabels:
      app: go-app
  replicas: 1 # tells deployment to run  pods matching the template
  template:
    metadata:
      labels:
        app: go-app
    spec:
      containers:
      - name: go-app
        image: 385591722563.dkr.ecr.us-east-1.amazonaws.com/myrepo:latest
        ports:
        - containerPort: 9005
        resources:
          limits:
            cpu: "1"
            memory: "200Mi"
          requests:
            cpu: "0.1"
            memory: "100Mi"
        
#              configMapKeyRef:
#                name: mssql-connection-configmap
#                key: db-connection-string
---
kind: Service
apiVersion: v1
metadata:
  name: go
spec:
  selector:
    app: go-app
  ports:
  - protocol: TCP
    port: 9005
    targetPort: 9005
  type: LoadBalancer