apiVersion: extensions/v1beta1

kind: Deployment

metadata:

  annotations:

    kompose.cmd: C:\Program Files\Kubernetes\kompose.exe convert -f docker-compose.yml

    kompose.version: 1.4.0 (c7964e7)

  creationTimestamp: null

  labels:

    io.kompose.service: mongodb

  name: mongodb

spec:

  replicas: 1

  strategy:

    type: Recreate

  template:

    metadata:

      creationTimestamp: null

      labels:

        io.kompose.service: mongodb

    spec:

      containers:

      - args:

        - --smallfiles

        image: 385591722563.dkr.ecr.us-east-1.amazonaws.com/mongo:latest

        name: mongodb

        ports:

        - containerPort: 27017

        resources: {}

        imagePullPolicy: Always # added manually

        volumeMounts:

        - mountPath: /data/db

          name: voter-data-vol

      restartPolicy: Always

      volumes:

      - name: voter-data-vol

        persistentVolumeClaim:

          claimName: voter-data-vol

status: {}
---
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Program Files\Kubernetes\kompose.exe convert -f docker-compose.yml
    kompose.version: 1.4.0 (c7964e7)
  creationTimestamp: null
  labels:
    io.kompose.service: mongodb
  name: mongodb
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    io.kompose.service: mongodb
status:
  loadBalancer: {}